
server:
  port: 8084

spring:
  application:
    name: NEWSAPIGATEWAY
  #config:
   # import: configserver:http://localhost:9296
  cloud:
    gateway:
      routes:
        - id: NEWS-SERVICE
          uri: lb://NEWS-SERVICE
          predicates:
            - Path=/news/**
          filters:
            - name: CircuitBreaker
              args:
                name: NEWS-SERVICE
                fallbackUri: forward:/newsServiceFallback
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
          filters:
            - name: CircuitBreaker
              args:
                name: USER-SERVICE
                fallbackUri: forward:/userServiceFallback

# Setup for user authentication with Okta using the Okta Spring Boot Starter.
okta:
  oauth2:
    issuer: https://dev-90308673.okta.com/oauth2/default
    audience: api://default
    client-id: 0oahruav06NxnuLHH5d7
    client-secret: 3kyuAX0QI8-aGfaTX4cGN5jSZl6erT2IDzp7On0MY2nQCMlfJZKYDXnApzPkdfVI
    scopes: openid, profile, email, offline_access

  # Configuration for applications to act as an OAuth2 Resource Server and Client
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: https://dev-90308673.okta.com/oauth2/default
      client:
        registration:
          internal-client:
            provider: okta
            authorization-grant-type: client_credentials
            scope: openid, profile, email, offline_access
            client-id: 0oahruav06NxnuLHH5d7
            client-secret: 3kyuAX0QI8-aGfaTX4cGN5jSZl6erT2IDzp7On0MY2nQCMlfJZKYDXnApzPkdfVI